apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: lsa-monitor
  namespace: monitoring
spec:
  namespaceSelector:
    matchNames:
    - agents
  selector:
    matchLabels: {}
  endpoints:
  - port: metrics
    interval: 15s
