apiVersion: v1
kind: ServiceAccount
metadata:
  name: cca-sa
  namespace: agents
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cca-role
rules:
- apiGroups: ["security.istio.io"]
  resources: ["authorizationpolicies"]
  verbs: ["get", "list", "create", "delete", "patch"]
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "patch"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cca-binding
subjects:
- kind: ServiceAccount
  name: cca-sa
  namespace: agents
roleRef:
  kind: ClusterRole
  name: cca-role
  apiGroup: rbac.authorization.k8s.io
